# Generated by Django 3.2.7 on 2021-09-28 14:10

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='ImageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, null=True, verbose_name='Название фото')),
                ('author_photo', models.ImageField(blank=True, upload_to='photo', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
            },
        ),
        migrations.CreateModel(
            name='TextBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, null=True, verbose_name='Заголовок блока')),
                ('main_information', models.CharField(blank=True, default='', max_length=512, verbose_name='Текст блока')),
            ],
            options={
                'verbose_name': '<Текстовый блок>',
                'verbose_name_plural': 'Текстовые блоки',
            },
        ),
        migrations.CreateModel(
            name='PhotoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, null=True)),
                ('front_image', models.ImageField(blank=True, upload_to='photo_front_img')),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
        migrations.AddIndex(
            model_name='photocard',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='mainapp_pho_title_cd722f_gin'),
        ),
    ]
