# Generated by Django 3.2.7 on 2021-09-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textblock',
            old_name='main_information',
            new_name='information',
        ),
        migrations.RemoveField(
            model_name='imageblock',
            name='author_photo',
        ),
        migrations.RemoveField(
            model_name='photocard',
            name='front_image',
        ),
        migrations.AddField(
            model_name='imageblock',
            name='image',
            field=models.ImageField(blank=True, upload_to='image', verbose_name='файл картинки'),
        ),
        migrations.AddField(
            model_name='photocard',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photo_img'),
        ),
        migrations.AlterField(
            model_name='imageblock',
            name='title',
            field=models.CharField(max_length=256, null=True, verbose_name='Название картинки'),
        ),
    ]
